### ISSUE TITLE
Value won't change after power off/on

### ISSUE THREAD

**Issue by shanyechungu** [tjpetz/BLESenseFlash#1]
Hi there, 

Thank you so much for this code. I wanted to use it to change a const value so that it can count the number of the device being turned on.

I modified your code to simply +1 each time it turns on. However, it doesn't seem to work. Would you please help check what is wrong with my code?

Thank you very much,

Here is my modified code based on yours:

#include <Arduino.h>

// nFR52 NVMC registers
#define NVMC_BASE       (0x4001E000U)
#define NVMC_READY      (NVMC_BASE + 0x400U)
#define NVMC_READYNEXT  (NVMC_BASE + 0x408U)
#define NVMC_CONFIG     (NVMC_BASE + 0x504U)
#define NVMC_ERASEPAGE  (NVMC_BASE + 0x508U)
#define NVMC_ERASEALL   (NVMC_BASE + 0x50CU)
#define NVMC_ERASEUICR  (NVMC_BASE + 0x514U)
#define NVMC_ERASEPAGEPARTIAL   (NVMC_BASE + 0X518U)
#define NVMC_ERASEPAGEPARTIALCFG  (NVMC_BASE + 0X51CU)
#define NVMC_ICACHECNF  (NVMC_BASE + 0x540U)
#define NVMC_IHIT       (NVMC_BASE + 0x548U)
#define NVMC_IMISS      (NMVC_BASE + 0x54cU)

const char PowerOffMemory[4096] __attribute__ ((section("FLASH2"), aligned (0x1000))) = {"1"}; 

int m = 0;
int NumberRegister;
char NumberCharRegister;

void hexDumpMemory(uint8_t *memStart, const unsigned int nbrOfBytes);

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  delay(2500);
  pinMode(LED_BUILTIN, OUTPUT);
  
//  NumberRegister = PowerOffMemory;
//  NumberCharRegister = NumberRegister;

  Serial.println(PowerOffMemory);
  NumberCharRegister = *(char *)(&PowerOffMemory);
  NumberCharRegister = NumberCharRegister + 1;
  
}

void loop() {
  
  if (m == 0)
  {
    
    hexDumpMemory((uint8_t *)(&PowerOffMemory), 16);
    
    if(*(uint32_t *)NVMC_READY == 1)
    {
      *(uint32_t *)NVMC_CONFIG = 0x02;
      *(uint32_t *)NVMC_ERASEPAGE = (uint32_t)(&PowerOffMemory);
      while(*(uint32_t *)NVMC_READY == 0)
      delay(100);
      *(uint32_t *)NVMC_CONFIG = 0x00;
    }

    if (*(uint32_t *)NVMC_READY == 1)
    {
      
      *(uint32_t *)NVMC_CONFIG = 0x01;
      *(uint32_t *)(&PowerOffMemory) = NumberCharRegister;
      while(*(uint32_t *)NVMC_READY == 0)
      delay(100);
      *(uint32_t *)NVMC_CONFIG = 0x00;
    }

    hexDumpMemory((uint8_t *)(&PowerOffMemory), 16);
    Serial.println(PowerOffMemory);
    
    m = 1;
  }

  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  digitalWrite(LED_BUILTIN, LOW);
  delay(100);
}

void hexDumpMemory(uint8_t *memStart, const unsigned int nbrOfBytes) {

  uint8_t *ptr;
  int bytesPerLine = 15;
  int bytesOnLine = 0;
  
  ptr = memStart;

  Serial.print("Memory dump of: "); Serial.println((unsigned long)(memStart), HEX);
  
  for (unsigned int i = 0; i < nbrOfBytes; i++) {
    if (bytesOnLine == 0) {
      Serial.print((unsigned long)(ptr+i), HEX);
      Serial.print(": ");
    }
    
    if (*(ptr+i) < 0x10)  // print a leading 0
      Serial.print("0");
    Serial.print(*(ptr+i), HEX); Serial.print(" ");
    
    if (bytesOnLine == bytesPerLine) {
      Serial.println(" ");
      bytesOnLine = 0;
    } else {
      bytesOnLine += 1;
    }
  }
}

**Comment by tjpetz** [comment]
A few things to look at... you're storing the count as a string rather than an integer.  Therefore when you initialize the flash memory you are putting the bytes 0x31 0x00 in memory.  This is different than putting an integer in there which would be 0x01 0x00 0x00 0x00.  Because you're using a string adding 1 to the value will work up through 9 but then you'll get a ':' character and subsequently onward through the sequence of ASCII codes.

I'd try shortening the delay in the write portions of your code.  delay() will delay for a specified number of milliseconds.  However the write time into flash is 41 micros seconds and the erase time is 85 milli seconds.  So your delay(100) is okay for the erase but the delay for the write is over a 1000 times too long.  Try using delayMicroseconds(50) for the write.  The excessively long delay for the write could be causing the processor to fail to update the flash memory.

**Comment by shanyechungu** [comment]
Yes, this is very helpful. Actually, I tried to change it to integer by defining the variable as below:

typedef struct flash_mem {
    uint16_t PlaceToStore;
    uint8_t PlaceHolder[4094];
} flash_mem_t;

const flash_mem_t myFlash __attribute__ ((section("FLASH2"), aligned (0x1000))) = {0, 0x00}; 

The value will be stored into the 16-bit integer and the rest of the page (PlaceHolder[4094]) are occupied so that no other stuff will be stored there and wiped off when erased which causes problems.

It works now.

However, I still have a question:

Can I make this integer 24 bits instead of 16? I cannot realize this. Would you please guide me on how to?

Thanks,

**Comment by tjpetz** [comment]
I'm glad you have it working.

Why do you want to use a 24 bit integer instead of a 16 or 32 bit integer?  

24 bit processors haven't been around since the 1970's except for some specialized Digital Signal Processors (DSPs).  Almost all processors will only process 8, 16, 32, or 64 bit integers but nothing in between.  If you really needed 24 bits you'd have to write your own math libraries.

Note, if you're thinking that 24 bits will give you the ability to track a greater number of turn on/off events (eg. > 64K) it won't.  The problem you'll run into is that you are only guaranteed 10,000 page erase events before the flash memory fails.  

Consider carefully the use of the on-chip flash memory and that limit of 10,000 page erase cycles.  When I created my code example I was developing it with the intent to store some BLE configuration settings which a user would normally change at most 10's of times in the lifetime of the application.  If you really need to record each time the chip is power cycled I suggest you use some external EEPROM memory (e.g. https://www.st.com/resource/en/datasheet/m24c02-f.pdf) which has a much higher number of write cycles... the one linked supports 4 million writes.
